import HeavyTailedNoise.Upper.K1.ActualBatchCrossTime

/-!
Two inputs for cross-time orthogonality: the actual whole-batch kernel error
is in `L²`, and an earlier error is measurable from the complete pre-batch
history of every later runtime batch.
-/

namespace HeavyTailedNoise.UpperK1

open MeasureTheory

noncomputable section

variable {q : ℝ} (P : Schedule q)

/-- Pull the proved product-space `L²` kernel error back to the original full
private/seed path. -/
theorem actualKernelBatchError_memLp_two {d : ℕ} {Seed : Type*}
    [MeasurableSpace Seed] (O : GradientOracle d Seed)
    (u : Fin P.T) (k : ℕ) :
    MemLp (actualKernelBatchError P O u k) 2
      ((algorithm (d := d) P).privateLaw.prod
        (freshSeedLaw O (responseCount P))) := by
  let globalLaw := (algorithm (d := d) P).privateLaw.prod
    (freshSeedLaw O (responseCount P))
  let targetLaw := (batchPastHistoryLaw P O u).prod (freshSeedLaw O P.n)
  let pathMap : (Fin P.T × (Fin (responseCount P) → Seed)) →
      BatchHistory P d u × (Fin P.n → Seed) := fun z =>
    (batchHistoryOfRun P O u z, batchSeedBlock P u z.2)
  have hmap : MeasurePreserving pathMap globalLaw targetLaw :=
    measurePreserving_actualHistory_currentBatch P O u
  have htarget : MemLp (kernelBatchErrorAtHistory P O u k) 2
      (Measure.map pathMap globalLaw) := by
    rw [hmap.map_eq]
    exact kernelBatchErrorAtHistory_memLp_two P O u k
  have hcomp := htarget.comp_of_map hmap.measurable.aemeasurable
  have hmeas : Measurable (actualKernelBatchError P O u k) :=
    (measurable_kernelBatchErrorAtHistory P O u k).comp
      ((measurable_batchHistoryOfRun P O u).prodMk
        ((measurable_batchSeedBlock P u).comp measurable_snd))
  apply hcomp.congr_norm hmeas.aestronglyMeasurable
  exact Filter.Eventually.of_forall (fun z => by
    rfl)

/-- Earlier complete-batch error is measurable in the full sigma-field
generated by the later batch's pre-batch transcript and private index. -/
theorem actualEarlierKernelError_measurable_prebatch
    {d : ℕ} {Seed : Type*} [MeasurableSpace Seed]
    (O : GradientOracle d Seed) (u v : Fin P.T)
    (huv : u.val < v.val) (k : ℕ) :
    Measurable[MeasurableSpace.comap
      (batchHistoryOfRun (d := d) P O v)
      (inferInstance : MeasurableSpace (BatchHistory P d v))]
      (actualKernelBatchError P O u k) := by
  let historyMap : (Fin P.T × (Fin (responseCount P) → Seed)) →
      BatchHistory P d v := batchHistoryOfRun P O v
  have hfun : actualKernelBatchError P O u k =
      earlierKernelErrorFromHistory P O u v huv k ∘ historyMap := by
    funext z
    exact actualKernelBatchError_eq_earlierHistory P O u v huv k z.1 z.2
  rw [hfun]
  exact (measurable_earlierKernelErrorFromHistory P O u v huv k).comp
    (comap_measurable historyMap)

end

end HeavyTailedNoise.UpperK1
