import HeavyTailedNoise.Lower.Gated.StartedStageObservationRecovery

/-!
Actual cumulative/latest sigma-algebra trace on the started branch.

The latest sigma-algebra is generated by the existing latest observation.
Every cumulative event is a preimage of a measurable path-space set.  The
checked observation recovery reconstructs that path from latest data on the
started branch, providing an explicit latest-measurable witness for its trace.
No history recovery or sigma-algebra equality is asserted off that branch.
Conditional expectations and the half bound are subsequent integration steps.
-/

namespace HeavyTailedNoise

open MeasureTheory ProbabilityTheory MeasurableSpace

noncomputable section

set_option autoImplicit false

def reconstructCumulativeObservation {d T N : ℕ} (j : Fin T)
    (z : IdealStageAnalysisData d T N) : Set.Iic j.val → IdealStageAnalysisData d T N :=
  fun i => reconstructEarlierObservation
    ⟨i.val, lt_of_le_of_lt (Set.mem_Iic.mp i.property) j.isLt⟩ j z

theorem measurable_reconstructCumulativeObservation {d T N : ℕ}
    (hT : 0 < T) (j : Fin T) :
    Measurable (reconstructCumulativeObservation (d := d) (N := N) j) := by
  apply measurable_pi_iff.mpr
  intro i
  exact measurable_reconstructEarlierObservation hT
    ⟨i.val, lt_of_le_of_lt (Set.mem_Iic.mp i.property) j.isLt⟩ j

theorem reconstructCumulativeObservation_eq_actual_of_started
    {d T N : ℕ} {Private : Type*} [MeasurableSpace Private]
    (hT : 0 < T) (U : Fin T → Point d) (j : Fin T)
    (A : RandomAlgorithm d N Private) (r : Private) (ξ : Fin N → Point d) (a : ℝ)
    (hs : (idealStoppedPreHistory hT U j A r ξ a).started = true) :
    reconstructCumulativeObservation j (idealStageObservation hT U A r ξ a j.val) =
      idealStageCumulativeData hT U A r ξ a j.val := by
  funext i
  exact reconstructEarlierObservation_eq_actual_of_started hT U
    ⟨i.val, lt_of_le_of_lt (Set.mem_Iic.mp i.property) j.isLt⟩ j
    (Set.mem_Iic.mp i.property) A r ξ a hs

@[instance_reducible] def idealLatestObservationSigma
    {d T N : ℕ} {Private Ω : Type*} [MeasurableSpace Private]
    (hT : 0 < T) (A : RandomAlgorithm d N Private) (r : Private) (a : ℝ)
    (U : Ω → Fin T → Point d) (ξ : Ω → Fin N → Point d) (j : Fin T) :
    MeasurableSpace Ω :=
  MeasurableSpace.comap (fun ω => idealStageObservation hT (U ω) A r (ξ ω) a j.val) inferInstance

def idealLatestStageActive
    {d T N : ℕ} {Private Ω : Type*} [MeasurableSpace Private]
    (hT : 0 < T) (A : RandomAlgorithm d N Private) (r : Private) (a : ℝ)
    (U : Ω → Fin T → Point d) (ξ : Ω → Fin N → Point d) (j : Fin T) : Set Ω :=
  {ω | (idealStageObservation hT (U ω) A r (ξ ω) a j.val).2.1 = true}

theorem idealLatestObservationSigma_le_cumulative
    {d T N : ℕ} {Private Ω : Type*}
    [MeasurableSpace Private] [mΩ : MeasurableSpace Ω]
    (hT : 0 < T) (A : RandomAlgorithm d N Private) (r : Private) (a : ℝ)
    (U : Ω → Fin T → Point d) (ξ : Ω → Fin N → Point d)
    (hU : Measurable U) (hξ : Measurable ξ) (j : Fin T) :
    idealLatestObservationSigma hT A r a U ξ j ≤
      idealStageFiltration hT A r a U ξ hU hξ j.val := by
  have hc : Measurable[idealStageFiltration hT A r a U ξ hU hξ j.val]
      (fun ω => idealStageCumulativeData hT (U ω) A r (ξ ω) a j.val) := by
    rw [idealStageFiltration_eq_cumulative]
    exact comap_measurable _
  exact ((measurable_pi_apply (⟨j.val, by simp⟩ : Set.Iic j.val)).comp hc).comap_le

theorem idealStageFiltration_le_ambient
    {d T N : ℕ} {Private Ω : Type*}
    [MeasurableSpace Private] [mΩ : MeasurableSpace Ω]
    (hT : 0 < T) (A : RandomAlgorithm d N Private) (r : Private) (a : ℝ)
    (U : Ω → Fin T → Point d) (ξ : Ω → Fin N → Point d)
    (hU : Measurable U) (hξ : Measurable ξ) (j : Fin T) :
    idealStageFiltration hT A r a U ξ hU hξ j.val ≤ mΩ :=
  (idealStageFiltration hT A r a U ξ hU hξ).le j.val

theorem measurableSet_idealLatestStageActive
    {d T N : ℕ} {Private Ω : Type*} [MeasurableSpace Private]
    (hT : 0 < T) (A : RandomAlgorithm d N Private) (r : Private) (a : ℝ)
    (U : Ω → Fin T → Point d) (ξ : Ω → Fin N → Point d) (j : Fin T) :
    MeasurableSet[idealLatestObservationSigma hT A r a U ξ j]
      (idealLatestStageActive hT A r a U ξ j) := by
  have ho : Measurable[idealLatestObservationSigma hT A r a U ξ j]
      (fun ω => idealStageObservation hT (U ω) A r (ξ ω) a j.val) := comap_measurable _
  have hb : Measurable[idealLatestObservationSigma hT A r a U ξ j]
      (fun ω => (idealStageObservation hT (U ω) A r (ξ ω) a j.val).2.1) :=
    measurable_fst.comp (measurable_snd.comp ho)
  exact hb (measurableSet_singleton true)

/-- Every cumulative-measurable event has a latest-measurable event with the
same trace on the actual started branch.  This is proved, not assumed. -/
theorem idealStageFiltration_trace_latest_on_started
    {d T N : ℕ} {Private Ω : Type*}
    [MeasurableSpace Private] [mΩ : MeasurableSpace Ω]
    (hT : 0 < T) (A : RandomAlgorithm d N Private) (r : Private) (a : ℝ)
    (U : Ω → Fin T → Point d) (ξ : Ω → Fin N → Point d)
    (hU : Measurable U) (hξ : Measurable ξ) (j : Fin T)
    (B : Set Ω) (hB : MeasurableSet[idealStageFiltration hT A r a U ξ hU hξ j.val] B) :
    ∃ C : Set Ω, MeasurableSet[idealLatestObservationSigma hT A r a U ξ j] C ∧
      B ∩ idealLatestStageActive hT A r a U ξ j =
        C ∩ idealLatestStageActive hT A r a U ξ j := by
  rw [idealStageFiltration_eq_cumulative] at hB
  obtain ⟨D, hD, hBD⟩ := (measurableSet_comap).mp hB
  let C : Set Ω := (fun ω => reconstructCumulativeObservation j
    (idealStageObservation hT (U ω) A r (ξ ω) a j.val)) ⁻¹' D
  have hC : MeasurableSet[idealLatestObservationSigma hT A r a U ξ j] C :=
    hD.preimage ((measurable_reconstructCumulativeObservation hT j).comp (comap_measurable _))
  refine ⟨C, hC, ?_⟩
  rw [← hBD]
  ext ω
  by_cases ha : ω ∈ idealLatestStageActive hT A r a U ξ j
  · have hidx : idealPrefixIndex hT j.val = j := by
      apply Fin.ext
      simp only [idealPrefixIndex]
      omega
    have hs : (idealStoppedPreHistory hT (U ω) j A r (ξ ω) a).started = true := by
      simpa only [idealLatestStageActive, Set.mem_ofPred_eq, idealStageObservation,
        hidx, idealPreResponseTuple] using ha
    have hr := reconstructCumulativeObservation_eq_actual_of_started hT (U ω) j A r (ξ ω) a hs
    simp only [C, Set.mem_inter_iff, Set.mem_preimage, hr]
  · simp [ha]

end

end HeavyTailedNoise
